# Generated by Django 5.1.3 on 2024-12-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_jobtitle_alter_user_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, choices=[('Tenaga Administrasi', 'Tenaga Administrasi'), ('Petugas Kebersihan', 'Petugas Kebersihan'), ('Petugas Keamanan', 'Petugas Keamanan'), ('Admin', 'Admin')], max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='JobTitle',
        ),
    ]
